# services:
  

#   mysql:
#     container_name: my_sql
#     image: mysql
#     networks:
#       - my-network
#     environment:
#       - MYSQL_ALLOW_EMPTY_PASSWORD=1

#   app:
#     image: alpine
#     build:
#      context: .
#     ports:
#       - "3000:80"
#     env_file:
#       - ./.env
#     networks:
#       - my-network

# networks:
#   my-network:
#     driver: bridge


services:

  php:
    build:
      context: .   
    depends_on:
       - mariadb 
    ports: 
      - "80:8181"  
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: forge
      DB_USERNAME: forge
      DB_PASSWORD: root
    

  mariadb:
    # container_name: maria_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: root
    volumes:
      - mariadb:/db
    ports:
      - '3306:3306'

volumes:
    mariadb: